### ISSUE TITLE
CI/CD Workflows Need to use Stable Tag

### ISSUE THREAD

**Issue by nutjob4life** [NASA-PDS/devops#19]
As part of our "lessons learned", having [PDS repositories](https://github.com/NASA-PDS) use the `main` branch of [Roundup Action](https://github.com/NASA-PDS/roundup-action) causes problems—namely, if a feature is implemented or a bug is fixed that _introduces_ a new bug, every repository using `main` is affected.

Instead, when we have a point in the Roundup development that we consider stable, we tag it with `stable`. A workflow YAML file can say:
```yaml
uses: NASA-PDS/roundup-action@stable
```
to say it prefers that tag of the action and not some other branch—especially not `main`.

The following repositories are still using the `@main` branch of the Roundup Action. These  should  should be transitioned to use `@stable`:
- [ ] api-search-query-lexer (awaiting [merge](https://github.com/NASA-PDS/api-search-query-lexer/pull/12))
- [ ] archive-analytics (awaiting [merge](https://github.com/NASA-PDS/archive-analytics/pull/24))
- [ ] harvest (awaiting [merge](https://github.com/NASA-PDS/harvest/pull/71))
- [ ] pds-api-javalib (awaiting [merge](https://github.com/NASA-PDS/pds-api-javalib/pull/13))
- [ ] pds-api-pythonlib (awaiting [merge](https://github.com/NASA-PDS/pds-api-pythonlib/pull/3))
- [ ] pds-api-service (awaiting [merge](https://github.com/NASA-PDS/pds-api-service/pull/4))
- [ ] pds-deep-archive (awaiting [mrege](https://github.com/NASA-PDS/pds-deep-archive/pull/123))
- [ ] pds-doi-service (awaiting [merge](https://github.com/NASA-PDS/pds-doi-service/pull/304))
- [ ] pds-registry-app (awaiting [merge](https://github.com/NASA-PDS/pds-registry-app/pull/215))
- [ ] pds-registry-common (awaiting [merge](https://github.com/NASA-PDS/pds-registry-common/pull/6))
- [ ] pds-registry-mgr-elastic (awaiting [merge](https://github.com/NASA-PDS/pds-registry-mgr-elastic/pull/38))
- [ ] pds-template-repo-java (awaiting [merge](https://github.com/NASA-PDS/pds-template-repo-java/pull/23))
- [ ] pds-template-repo-python (awaiting [merge](https://github.com/NASA-PDS/pds-template-repo-python/pull/53))
- [ ] pds4-information-model (awaiting [merge](https://github.com/NASA-PDS/pds4-information-model/pull/422))
- [ ] pds4-jparser (awaiting [merge](https://github.com/NASA-PDS/pds4-jparser/pull/51))
- [ ] pdsen-maven-parent (awaiting [merge](https://github.com/NASA-PDS/pdsen-maven-parent/pull/3))
- [ ] registry-api-service (awaiting [merge](https://github.com/NASA-PDS/registry-api-service/pull/92))
- [ ] supplementer (awaiting [merge](https://github.com/NASA-PDS/supplementer/pull/5))

**Comment by jordanpadams** [comment]
@nutjob4life oops! I may have jumped the gun here with validate and pds4-jparser. just realized we don't actually have a `stable` branch yet. once we have that, we can test this out.

**Comment by nutjob4life** [comment]
@jordanpadams the `@stable` refers to the tag on `roundup-action`, not on `validate` or `pds4-japrser`.

Also it's doubly-fine right now because `roundup-action@main == roundup-action@stable` 😌

**Comment by jordanpadams** [comment]
@nutjob4life copy. i was thinking i didn't see the branch but I see the tag 😨
