### ISSUE TITLE
Update documentation for creating new repo to add DOI webhook

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/devops#20]
## 💡 Description

Update https://github.com/NASA-PDS/nasa-pds.github.io/wiki/Git-and-Github-Guide#creating-a-new-repo with the info necessary to enable DOIs for a particular repo when applicable.

Follow-on to #14

**Comment by nutjob4life** [comment]
Progress update:

Docs updated in wiki in e32fb075d2d66a47a222b1484aea43a9b5fb0738 and a note about badges in db0476f51236243e1a145229e8086fdf70ed7a5b.

**Comment by jordanpadams** [comment]
Just tested it out and added a few more repos.
