### ISSUE TITLE
NASA-PDS group on Zenodo should belong to a group account, not an individual

### ISSUE THREAD

**Issue by nutjob4life** [NASA-PDS/devops#21]
Currently the [NASA-PDS group](https://zenodo.org/communities/nasa-pds/) on Zenodo (what they call a "community") belongs to the GitHub user @nutjob4life, who is then responsible for listing newly-assigned DOIs in the group.

Zenodo says that "having multiple curators per community is an oft-requested feature" but is "currently not supported" and is recommended that "a single account that an organization has shared access to" be assigned the ownership role.

We have such an account: @pdsen-ci.

Please have it take over the `NASA-PDS` community on Zenodo.

**Comment by nutjob4life** [comment]
Progress report: requested ownership changed from @nutjob4life to @pdsen-ci via Message-ID: `<3657ca33-56d5-82a0-203f-3b4ee37373c3@seankelly.biz>` on 2021-12-01T17:55:18Z.

**Comment by nutjob4life** [comment]
Confirmed. We can close this issue out now @jordanpadams @tloubrieu-jpl 

To test:

1. Visit http://zenodo.org/ with a private (incognito) browser.
2. Click "🚪 Log in" in the upper right
3. Click "🐱 Log in with GitHub"
4. At the GitHub credential prompt, use the `pdsen-ci` credential and password, then click Sign in.
5. Once redirected back to Zenodo, click Communities in the navigation bar.
6. Under "My communities" notice "NASA Planetary Data System".

**Comment by jordanpadams** [comment]
looks fantastic!
<img width="1206" alt="Screen Shot 2021-12-03 at 1 39 14 PM" src="https://user-images.githubusercontent.com/33492486/144677264-94198bd4-72b4-4ca3-ad7a-3a1eff12ae1d.png">

@nutjob4life any idea who this TESTPERSONNEL is?

**Comment by nutjob4life** [comment]
@jordanpadams I correlated the contributions listed by Zenodo with those on GitHub and 9/10 match except for this one: Dependabot. 

Maybe that's who "TESTPERSONAL" is?

Wait a minute … calling GitHub API to list contributors … 
```console
$ curl --silent --header 'Accept: application/vnd.github.v3+json' --user 'kelly:[REDACTED]' https://api.github.com/repos/NASA-PDS/harvest/contributors | egrep TESTPERSONAL
    "login": "TESTPERSONAL",
    "url": "https://api.github.com/users/TESTPERSONAL",
    "html_url": "https://github.com/TESTPERSONAL",
    "followers_url": "https://api.github.com/users/TESTPERSONAL/followers",
    "following_url": "https://api.github.com/users/TESTPERSONAL/following{/other_user}",
    "gists_url": "https://api.github.com/users/TESTPERSONAL/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/TESTPERSONAL/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/TESTPERSONAL/subscriptions",
    "organizations_url": "https://api.github.com/users/TESTPERSONAL/orgs",
    "repos_url": "https://api.github.com/users/TESTPERSONAL/repos",
    "events_url": "https://api.github.com/users/TESTPERSONAL/events{/privacy}",
    "received_events_url": "https://api.github.com/users/TESTPERSONAL/received_events",
```
This is a real GitHub user: https://github.com/TESTPERSONAL … apparently joined GitHub on February 12, 2014. But has no significant contributions.

Maybe it's a bug?  WAIT a sec! Look at this:
```console
$ cd /tmp
$ git clone --quiet git@github.com:NASA-PDS/harvest.git
$ cd harvest
$ git log | egrep '^Author: ' | sort -u
Author: Eugene <karpenko@RAYL-AI846797.jpl.nasa.gov>
Author: Eugene <test@test.com>
Author: Eugene <tumbao72@yahoo.com>
Author: Galen A Hollins <Galen.A.Hollins@jpl.nasa.gov>
Author: GitHub Action <action@github.com>
Author: Jordan H Padams <Jordan.H.Padams@jpl.nasa.gov>
Author: Jordan Padams <33492486+jordanpadams@users.noreply.github.com>
Author: Jordan Padams <jordan.h.padams@jpl.nasa.gov>
Author: Michael Cayanan <michael.cayanan@jpl.nasa.gov>
Author: Mike Cayanan <michael.d.cayanan@jpl.nasa.gov>
Author: PDS dev admin <pdsen-ci@github.com>
Author: PDSEN CI Bot <pdsen-ci@jpl.nasa.gov>
Author: Sean Hardman <Sean.Hardman@jpl.nasa.gov>
Author: Sean Kelly <kelly@seankelly.biz>
Author: U-JPL\karpenko <karpenko@RAYL-AI846797.jpl.nasa.gov>
Author: Yevgen Karpenko <yevgen.l.karpenko@jpl.nasa.gov>
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Author: ghollins <Galen.A.Hollins@jpl.nasa.gov>
Author: jpadams <jpadams@45d5965c-88be-4637-9056-144873d6cd01>
Author: mcayanan <mcayanan@45d5965c-88be-4637-9056-144873d6cd01>
Author: shardman <shardman@45d5965c-88be-4637-9056-144873d6cd01>
Author: thomas loubrieu <60993872+tloubrieu-jpl@users.noreply.github.com>
Author: thomas loubrieu <thomas.loubrieu@jpl.nasa.gov>
```
Look at that second line. Eugene made a commit using email address `test@test.com`, which I would wager is what TESTPERSONAL's email address it.

I bet it's @tdddblog!

In any case, we can override the authors that Zenodo figures out in the `.zenodo.json` file if you like.

**Comment by tdddblog** [comment]
@nutjob4life yes that's my current `git config --global user.email`. I can set local email for PDS projects. What is the best value? My real PDS email?

**Comment by jordanpadams** [comment]
> @nutjob4life yes that's my current `git config --global user.email`. I can set local email for PDS projects. What is the best value? My real PDS email?

@tdddblog whatever your email address is associated with your Github.com account would be best.

**Comment by nutjob4life** [comment]
![lalaine-dawn-lalaine-dawn-tv](https://user-images.githubusercontent.com/814813/145037351-2ff62b4f-88c2-4fbd-a87d-38065ddff1eb.gif)
