### ISSUE TITLE
As a developer, I want access to the latest and continuously deployed exposition API

### ISSUE THREAD

**Issue by nutjob4life** [NASA-PDS/devops#22]
## 💪 Motivation
...so that I can run clients against an API server without needing the expertise to set up an API server

## 📖 Additional Details

The [parent epic ticket](https://github.com/NASA-PDS/devops/issues/11) as well as the [deployment lifecycle diagram](https://lucid.app/lucidchart/20488354-9ead-46c0-8d86-f44c7604ca98/edit?viewport_loc=-184%2C-19%2C2048%2C1172%2C0_0&invitationId=inv_d870c829-346b-4bf7-8146-181712b3e178) provide context and additional details.

## ⚖️ Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect**

**Comment by tloubrieu-jpl** [comment]
maybe, instead of /expo we want /api/search/latest/ 

And for the DOI endpoint:
/api/doi/0.2/

**Comment by nutjob4life** [comment]
The Exposition Server now uses Jenkins pipelines to continuously (nightly) deploy the following services:

- [DOI](https://pds-dev-doi.jpl.nasa.gov/PDS_APIs/pds_doi_api/0.2/ui/)
- [Registry](https://pds-dev-registry.jpl.nasa.gov/)

**Comment by tloubrieu-jpl** [comment]
I will close this ticket and create a new one to have the url scheme match what we have in production.

**Comment by tloubrieu-jpl** [comment]
Follow up ticket is https://github.com/NASA-PDS/devops/issues/29
