### ISSUE TITLE
Develop github action to publish docker images on docker hub

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/devops#23]
## 💪 Motivation
...so that we don't have to do it manually build and publish the images.

## 📖 Additional Details

consider the publication on AWS ECR for later

## ⚖️ Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect**

**Comment by nutjob4life** [comment]
Pull requests made for the following repositories that produce Docker images:

- [ ] [registry-api](https://github.com/NASA-PDS/registry-api/); [pull request](https://github.com/NASA-PDS/registry-api/pull/107) awaiting review 🔍
- [ ] [registry-loader](https://github.com/NASA-PDS/registry-loader); [pull request](https://github.com/NASA-PDS/registry-loader/pull/8) awaiting review 🔍
- [ ] [registry-harvest-service](https://github.com/NASA-PDS/registry-harvest-service) [pull request](https://github.com/NASA-PDS/registry-harvest-service/pull/20) awaiting review 🔍
- [ ] [registry-crawler-service](https://github.com/NASA-PDS/registry-crawler-service); [pull request](https://github.com/NASA-PDS/registry-crawler-service/pull/18) awaiting review 🔍 
- [ ] [registry-harvest-cli](https://github.com/NASA-PDS/registry-harvest-cli) … accidentally pushed to `main` 😆
