### ISSUE TITLE
Automatic image creation needs to parameterize Dockerfile

### ISSUE THREAD

**Issue by nutjob4life** [NASA-PDS/devops#24]
The automatic image creation recently added to several repositories ([registry-api](https://github.com/NASA-PDS/registry-api/), [registry-loader](https://github.com/NASA-PDS/registry-loader), [registry-harvest-service](https://github.com/NASA-PDS/registry-harvest-service), [registry-crawler-service](https://github.com/NASA-PDS/registry-crawler-service), and [registry-harvest-cli](https://github.com/NASA-PDS/registry-harvest-cli)) seems to take into account only `Dockerfile`. 

However, some of the repositories use `Dockerfile.local` and other `Dockerfiles`. The automatic image creation should figure out which of these to use for stable and unstable workflows.

**Comment by jordanpadams** [comment]
resolved per https://github.com/NASA-PDS/registry-api/pull/120
