### ISSUE TITLE
As a developer, I want to have a documentation for the Continuous Deployment in the DEV STAGING venue

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/devops#27]
## 💪 Motivation
...so that I can check if that works, so that I can add an application.

## 📖 Additional Details

We need a documentation to access the jenkins server and check that deployment work and to be able to add new applications.

I would expect this documentation to be around there https://wiki.jpl.nasa.gov/display/PDSEN/Developer+Guides since it is dedicated to the dev team and not available outside JPL.

## ⚖️ Acceptance Criteria
**Given** the PDS Engineering node internal documentation
**When I perform** go to the devlopers guidelines
**Then I expect** to find a documentation for the jenkins platform and the CD on the DEV STAGING venue

**Comment by nutjob4life** [comment]
Documentation written with several formats available (including Confluence wiki—see the file `jenkins.jira`) in the attached zip archive.

[jenkins.zip](https://github.com/NASA-PDS/devops/files/8913309/jenkins.zip)

@tloubrieu-jpl please review and if it looks okay, please post to the wiki of your preference! 👍

**Comment by tloubrieu-jpl** [comment]
Thanks @nutjob4life , I published your page on https://wiki.jpl.nasa.gov/pages/viewpage.action?pageId=611827250

**Comment by tloubrieu-jpl** [comment]
Actually, what I was looking for in addition to what you wrote, is a way to quickly find the url to a deployment on DEV STAGING, per deployed application, e.g. registry-api, doi editor.

I guess it is on http://pds-expo.jpl.nasa.gov/ but then I have to guess which subpath point to be application I am interested it, for example http://pds-expo.jpl.nasa.gov/api/latest/search/products (for the registry-api but that does not work).

May be this is available somewhere, you ideas are welcome as well. That might be part of the deployment guide where we could have urls for each venues, see https://wiki.jpl.nasa.gov/display/PDSEN/Software+Installation+and+Deployment+Guides

your ideas are welcome. I might create different ticket for that.
