### ISSUE TITLE
Investigate Harness as a possible DevOps CD solution

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/devops#28]

**Comment by tloubrieu-jpl** [comment]
@nutjob4life is having a meeting with Harness at 1pm PCT tomorrow.

**Comment by tloubrieu-jpl** [comment]
@nutjob4life had the meeting, and is using a trial server still available for 2 weeks.

**Comment by tloubrieu-jpl** [comment]
@nutjob4life was able to do end-to-end demos locally and on harness premises.

**Comment by tloubrieu-jpl** [comment]
@nutjob4life will do a demo at the breakout this Tuesday. We'll decide there:
- what deployment strategy (blue/green, rollover)
- should we o on with Harness
- will that work on NGAP

**Comment by tloubrieu-jpl** [comment]
The demo is on https://jpltube.jpl.nasa.gov/Watch=hk3GRA

**Comment by tloubrieu-jpl** [comment]
Thanks for the demo @nutjob4life , a little disappointed but it sounds like it could work.

**Comment by tloubrieu-jpl** [comment]
Addiing email from Jason on the usuability of harness on NGAP:
Sean,
 
Looking at the Harness information, I think that you will be able to deploy it to the NGAP accounts.  It seems they support deploying the delegate in EKS (Elastic Kubernetes) or in ECS (Elastic containers) and we allow the use of either of those in NGAP accounts. 
 
We may need to do some network configuring to allow access to Harness but for development work you could use tunneling from your local machine to achieve this as well, I think.
 
We do have Bamboo for some of our NGAP tenants, but this is provided by the ESDIS project for most of those tenants.  That said, I’m sure in some circumstances PDS could use Bamboo as well, but we also wouldn’t preclude you using a different CICD package or even in running that CICD within the NGAP environment.
 
Also, I want to point out that the NGAP presentations you linked to are now pretty out of date.  The later one does talk a little bit about our change in posture about how we manage the environment for tenants and we are now much more open to tenants using more native AWS Services (like the EKS and ECS mentioned above).  However, I do need to note here that the requested access for Apache Airflow in AWS is still in progress, I hope to have more information on allowing that in NGAP soon.  But for Harness, I think all the services you need should be available.
 
Please let me know if you have more questions.
 
Thanks,

**Comment by tloubrieu-jpl** [comment]
@jordanpadams is taking care of the costs
