### ISSUE TITLE
Make the DOI service Dev staging deployment initialized with non empty database

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/devops#30]
## 💡 Description

The database an sqllite file stored at the root of the virtual environment (doi.db).

The following command initialize the database with the PDS's dataCite dois:

    pds-doi-init --service datacite --prefix ${PREFIX} --submitter ${SUBMITTER}

Where submitter is the email of the author of the operation and prefix is one of 10.17189, 10.26007, 10.2603 (to be confirmed with @jordanpadams which one is best in this case). We would get the DOIs from the dataCite test database anyway to avoid sharing the production login/password on the staging area and risking them to be used to update the production DOIs.

**Comment by nutjob4life** [comment]
This is in progress, but I need @jordanpadams to answer this question:

What should `${PREFIX}` be?

- `10.17189`
- `10.26007`
- or `10.2603`?

**Comment by jordanpadams** [comment]
@nutjob4life 10.17189

**Comment by jordanpadams** [comment]
@nutjob4life since you are using the test database, I'm not sure what, if anything will come back with our operations prefix? If nothing gets populated in the database, try our test prefix `10.13143`
