### ISSUE TITLE
jenkins continuous deployment does not pull docker images

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/devops#34]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

The docker images used in the registry pipeline are not updated.

### 🕵️ Expected behavior

I expected the newest latest images to be pulled every night.

### 📜 To Reproduce

Go on the jenkins https://pds-jenkins.jpl.nasa.gov/job/Registry/

### 🦄 Related requirements

🦄 #xyz

**Comment by nutjob4life** [comment]
Note I've [filed a ticket for this issue earlier](https://github.com/NASA-PDS/registry/issues/175) specifically for the Registry. But a similar problem almost assuredly exists for [the DOI service](https://github.com/NASA-PDS/doi-service) too.

**Comment by nutjob4life** [comment]
See

- [Original issue reported on Registry](https://github.com/NASA-PDS/registry/issues/175)
- [Pull request for Registry](https://github.com/NASA-PDS/registry/pull/177)
- [Pull request for DOI service](https://github.com/NASA-PDS/doi-service/pull/402)
