### ISSUE TITLE
As a EN team member, I want to check the API test reports in testrail

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/devops#35]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

EN team member

### 💪 Motivation

...so that I can report on the automatic testing.

### Acceptance Criteria

**Given** the jenkins dev staging server, testrail production service
**When I perform** when I go to the testrail run report https://cae-testrail.jpl.nasa.gov/testrail/index.php?/runs/overview/168 
**Then I expect** to see nighty test reports for the suite PDS Registry API, automated tests (https://cae-testrail.jpl.nasa.gov/testrail/index.php?/suites/view/12824&group_by=cases:section_id&group_order=asc)

### ⚙️ Engineering Details

Follow the guidelines on https://medium.com/apis-with-valentine/how-to-integrate-testrail-with-postman-newman-api-tests-cc0380998d04

Use test suite in testrail https://cae-testrail.jpl.nasa.gov/testrail/index.php?/suites/view/12824 for API automated testing.

Use test with ID: C1274687

Add the reference in the postman test suite in the registry repository, see https://github.com/NASA-PDS/registry/tree/main/docker/postman

Update the newman configuration for the jenkins pipeline so that jenkins generates a nightly test report on test rail. That will be a single test for now, but we want that to be a starting point for the I&T team to get a full reporting on the postman tests in test rail.

**Comment by tloubrieu-jpl** [comment]
@nutjob4life will need a testrail account for that

**Comment by jordanpadams** [comment]
@viviant100 @miguelp1986 can you help get @nutjob4life an account for this?

**Comment by viviant100** [comment]
Sure, I put in a request. Waiting for approval.

**Comment by nutjob4life** [comment]
I am _so close_ on this, but currently blocked by an issue in the Newman TestRail Reporter:

https://github.com/billylam/newman-reporter-testrail/issues/60

Time permitting I'll fork that repo and put in the support for CAE TestRail

**Comment by tloubrieu-jpl** [comment]
@nutjob4life submitted a bug in the test reporter, he is going to propose a PR

**Comment by nutjob4life** [comment]
The owner of `newman-reporter-testrail` has suggested a workaround which I can confirm works, so moving forward.
