### ISSUE TITLE
Transition away from `::set-output` in GitHub Workflows

### ISSUE THREAD

**Issue by nutjob4life** [NASA-PDS/devops#43]
## 💡 Description

The [GitHub Actions Blog](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) reminds us that using `::set-output` (and `::save-state`) is deprecated for security reasons and to use `echo "NAME=VALUE" >> $GITHUB_OUTPUT` instead. (I don't think we're using `::save-state` at all.)

The repositories that may affect includes:

- [registry-api](https://github.com/NASA-PDS/registry-api)
- [registry-crawler-service](https://github.com/NASA-PDS/registry-crawler-service)
- [registry-harvest-cli](https://github.com/NASA-PDS/registry-harvest-cli)
- [registry-harvest-service](https://github.com/NASA-PDS/devops)

**Comment by alexdunnjpl** [comment]
No usage found in `registry-crawler-service`, `registry-harvest-cli` or `registry-harvest-service`.

Template repos checked too - no old-style usage.

**Comment by alexdunnjpl** [comment]
[PR open for registry-api](https://github.com/NASA-PDS/registry-api/pull/332) - closing on that basis
