### ISSUE TITLE
Ask new Application developer profile on JPL AWS

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/devops#44]
## 💡 Description

Ask SAs

**Comment by tloubrieu-jpl** [comment]
@tloubrieu-jpl created a ticket to the SAs

**Comment by tloubrieu-jpl** [comment]
@tloubrieu-jpl need to answer our SAs questions

**Comment by tloubrieu-jpl** [comment]
Answer to the Sa,s question in elaborated in spreadsheet https://docs.google.com/spreadsheets/d/17q6Aye5jH2HM6tLcNp7WDxIUu04fQUMUv1U0JGicPiQ/edit#gid=956249108

We decided to focus on nucleus, registry and there dependencies for the new dev profile.

**Comment by nutjob4life** [comment]
No date yet

**Comment by nutjob4life** [comment]
Sagar reports that we're not quite sure how to use this yet. This doesn't let you log into AWS console. It's a role attached to a deployment node for Jenkins. By using this agent, you can deploy certain resources that you couldn't heretofore. You should be able to terraform-login. Sagar will get more clarification from SA team on how to use it.

**Comment by tloubrieu-jpl** [comment]
To be checked by Sagar when he is going to work on the Jenkins.

This ticket is tabled.

**Comment by tloubrieu-jpl** [comment]
We don't need that anymore since we are moving to MCP.
