### ISSUE TITLE
Use Github Actions Github-Hosted Runner to deploy to NGAP

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/devops#45]
## 💡 Description

@nutjob4life knows how to do that, @sjoshi-jpl has access to NGAP.

**Comment by sjoshi-jpl** [comment]
@tloubrieu-jpl since @nutjob4life is out of office until 29th, I'll start going through the steps provided on [GitHub Docs](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/adding-self-hosted-runners). Will reach out incase of roadblocks.

**Comment by tloubrieu-jpl** [comment]
There are security concerns in having a self-hosted runner on public gihub repository. 

@sjoshi-jpl will keep on exploring the self hosted solution until next breakout, so that we can decide if we have an easy enough / secured enough solution with the self hosted runners.

**Comment by sjoshi-jpl** [comment]
@tloubrieu-jpl @jordanpadams I am able to successfully execute Terraform plan using GitActions in NGAP. Currently I am using the github-hosted runner with OIDC setup we discussed over the call yesterday.

Successful run -
https://github.com/NASA-PDS/monitoring/actions/runs/5072130455/jobs/9109653549

**Comment by jordanpadams** [comment]
@sjoshi-jpl noticed issue with OICD auth timeout issue. working at Jenkins to do this as well to have 2 ways to deploy

**Comment by tloubrieu-jpl** [comment]
Hi @sjoshi-jpl , before I close this ticket can you create some documentation and link it here.

I think the best place would be on our internal wiki. 

Thanks

**Comment by tloubrieu-jpl** [comment]
The documentation would mostly point to how the NGAP configuration (OICD ?) has been made and pointing to the workflows developed in this repository.

**Comment by sjoshi-jpl** [comment]
@tloubrieu-jpl  I've created a document on internal wiki as requested. Please review and let me know if additional info is needed.

https://wiki.jpl.nasa.gov/pages/viewpage.action?pageId=779056783

**Comment by tloubrieu-jpl** [comment]
Ok, that looks good @sjoshi-jpl . I added a context section. We are good for this ticket.
