### ISSUE TITLE
As an EN developer, I want to make sure I have access to all PDS repos.

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/devops#5]
For more information on how to populate this new feature request, see the PDS Wiki on User Story Development:

https://github.com/NASA-PDS/nasa-pds.github.io/wiki/Issue-Tracking#user-story-development

## Motivation
...so that I can update / access any of our repositories and source code at any time.

## Additional Details
We should make sure all of our repos have the following teams with access:
* @pds-software-committers - Write
* @pds-software-pmc - Admin
* @pdsen-operations - Admin

Additionally, not sure if doing this autonomously is worth the effort at this point. Let's just add this to the template repo READMEs or in a wiki for creating a new repo and call it good.

## Acceptance Criteria
**Given** a member of the @pds-software-committers team has an update to push to a PDS EN repo
**When I perform** a commit and push to a branch
**Then I expect** to successfully push to a branch on that repo

**Given** a member of the @pds-software-pmc or @pdsen-operations team has an update to push to a PDS EN repo
**When I perform** a commit and push to master on that repo
**Then I expect** to successfully push to master on that repo

**Comment by nutjob4life** [comment]
I've updated the [wiki page about new repos](https://github.com/NASA-PDS/nasa-pds.github.io/wiki/Git-and-Github-Guide) to refine the advice on team setup. Doing the READMEs for the `-java` and `-python` repositories next.

**Comment by jimmie** [comment]
Finito.
