### ISSUE TITLE
Add GitHub Actions terraform workflow to Python & Java Template Repos

### ISSUE THREAD

**Issue by sjoshi-jpl** [NASA-PDS/devops#52]
## 💡 Description

When new repos are created using the [Python ](https://github.com/NASA-PDS/template-repo-python)and [Java](https://github.com/NASA-PDS/template-repo-java) Template Repos, they should also have a default terraform workflow.

**Comment by jordanpadams** [comment]
This task is complete per https://github.com/NASA-PDS/template-repo-python/pull/74 and https://github.com/NASA-PDS/template-repo-java/pull/29
