### ISSUE TITLE
Deploy Registry-API using Terraform in NGAP

### ISSUE THREAD

**Issue by sjoshi-jpl** [NASA-PDS/devops#54]
## 💡 Description

Configure all deployable components of Registry API using Terraform. Also create Terrafrom workflow for Continuous Deployment using Github actions.

The scope of this task will include re-architecting how registry-api image gets deployed. Ideally with every push to main, we want to deploy a new docker image on ECR and have Terraform workflow use it to deploy / configure the ECS infrastructure.

**Comment by nutjob4life** [comment]
Sagar reports: in progress, no blockers ATM

**Comment by tloubrieu-jpl** [comment]
NGAP is not a deployment target anymore for PDS. We use MCP instead and deployment work with MCP as described in ticket https://github.com/NASA-PDS/registry-api/issues/509
