### ISSUE TITLE
Develop React/NodeJS template repo

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/devops#61]
## 💡 Description

This probably doesn't need to be as comprehensive as the Java/Python repos, but we should have something here to house some of our best practices and CI/CD stuff

- How to build
- How to test
- Static code analysis requirements
- Security scanning requirements prior to production release

**Comment by jordanpadams** [comment]
Completed several weeks ago. https://github.com/NASA-PDS/template-repo-nodejs/

**Comment by nutjob4life** [comment]
Thanks @jordanpadams! And if I may say so, it's fairly comprehensive too 😁
