### ISSUE TITLE
Develop Stable GitHub Action CI

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/devops#64]
## 💡 Description

Merge to `main` -> run CI and tag stable release

**Comment by nutjob4life** [comment]
I believe this [pull request](https://github.com/NASA-PDS/roundup-action/pull/135) will close the following issues

- #63
- #64 
- #66 
- #69

**Comment by jordanpadams** [comment]
Cut down the scope of this task to just CI. Will close and create new CD ticket.
