### ISSUE TITLE
Develop Initial Architecture and Action Flow for React CI/CD Deployments

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/devops#66]
## 💡 Description

Can start with our existing lucid diagram: https://lucid.app/lucidchart/20488354-9ead-46c0-8d86-f44c7604ca98/edit?invitationId=inv_d870c829-346b-4bf7-8146-181712b3e178

**Comment by nutjob4life** [comment]
I believe this [pull request](https://github.com/NASA-PDS/roundup-action/pull/135) will close the following issues

- #63
- #64 
- #66 
- #69

**Comment by jordanpadams** [comment]
Closed per https://github.com/NASA-PDS/roundup-action/pull/135
