### ISSUE TITLE
Develop baseline CI/CD for React Projects

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/devops#67]
## 💡 Description

Laying the groundwork for a future roundup requirement, let's create a new GitHub Action in a repo using NPM and test our what we want/need in order to support it.

For now, let's just build out the branch testing, unstable, and stable deliveries:

branch-cicd.yaml - install dependencies, build, verify success:
* https://github.com/NASA-PDS/wds-react#prerequisite
* https://github.com/NASA-PDS/wds-react#build-the-packages

unstable-cicd.yaml - install dependencies, build, deploy to dev npm (NOTE: requires package.json to already be updated as indicated in README):
* https://github.com/NASA-PDS/wds-react#prerequisite
* https://github.com/NASA-PDS/wds-react#build-the-packages
* `npm publish --tag beta`

stable-cicd.yaml - install dependencies, build, deploy to dev npm (NOTE: requires package.json to already be updated as indicated in README):
* https://github.com/NASA-PDS/wds-react#prerequisite
* https://github.com/NASA-PDS/wds-react#build-the-packages
* `npm publish`

### Associated requirement
- 🦄 https://github.com/NASA-PDS/devops/issues/68

### Sub-tasks
- ~https://github.com/NASA-PDS/wds-react-legacy/issues/95~
- ~https://github.com/NASA-PDS/devops/issues/66~
- ~https://github.com/NASA-PDS/devops/issues/61~
- https://github.com/NASA-PDS/devops/issues/68
- ~https://github.com/NASA-PDS/devops/issues/62~
- ~https://github.com/NASA-PDS/devops/issues/63~
- ~https://github.com/NASA-PDS/devops/issues/64~
- ~https://github.com/NASA-PDS/devops/issues/65~

**Comment by jordanpadams** [comment]
📆 October status: Delayed start due to other roundup-action tickets. Will hopefully catch up in November. No impact on build deliveries anticipated.

**Comment by jordanpadams** [comment]
📆 November status: Initial components defined. Awaiting implementaiton.

**Comment by jordanpadams** [comment]
@nutjob4life here is the parent Epic for this task with a breakdown of what I think may need to be done. Obviously this can be changed, but just jotted down some ideas a couple months ago

**Comment by nutjob4life** [comment]
@jordanpadams 🎉 thanks!

**Comment by jordanpadams** [comment]
📆 December status: In work. On schedule.

**Comment by jordanpadams** [comment]
📆 01/2024 status: In work. On schedule.

**Comment by jordanpadams** [comment]
@nutjob4life Where are we at with this? Are we unblocked and ready to proceed to some of these other tasks?

**Comment by jordanpadams** [comment]
📆 02/2024 status: Closing this out as "Phase 1". will move many sub-tasks to continued work in B15.0. No impact on delivery since this is an internal team optimization.

**Comment by jordanpadams** [comment]
@nutjob4life moving next phase here; https://github.com/NASA-PDS/devops/issues/69

**Comment by nutjob4life** [comment]
> @nutjob4life Where are we at with this? Are we unblocked and ready to proceed to some of these other tasks?

Hi @jordanpadams! For some reason, I've been mostly tracking this in #63 (see the numerous and voluminous comments there—as well as [this answer](https://jpl.slack.com/archives/GCGR1R3A4/p1703700324138809?thread_ts=1703283193.944499&cid=GCGR1R3A4)). However, finishing up the Roundup Action's support for Node.js is—thanks to @anilnatha—completely unblocked. I'll continue to track in #69.
