### ISSUE TITLE
Terraform Immersion

### ISSUE THREAD

**Issue by nutjob4life** [NASA-PDS/devops#70]
### 💡 Description

@tloubrieu-jpl recommends that @ramesh-maddegoda and @sjoshi-jpl help @nutjob4life immerse himself into the world of Terraform.

This ticket is to track scheduling, progress, and metrics for immersion success—shallow, deep, thoroughly soaked, etc.

**Comment by nutjob4life** [comment]
Hi @ramesh-maddegoda and @sjoshi-jpl, I've created a [straw poll](https://strawpoll.com/eJnvvbQEGnv) to help figure out a time when we can meet and do this "immersion". Please respond when you can.

**Comment by nutjob4life** [comment]
Thanks @sjoshi-jpl and @ramesh-maddegoda for answering the straw poll.

The date of the meeting shall be Wednesday, 3rd of April, at noon pacific (2pm central). See the JPL Outlook calendar for the Teams meeting details.

**Comment by tloubrieu-jpl** [comment]
Meeting tomorrow to introduce Sean to terraform used in PDS ENG.

**Comment by nutjob4life** [comment]
My ISP is down so will reschedule. Also @viviant100  would like to join

**Comment by nutjob4life** [comment]
@ramesh-maddegoda @sjoshi-jpl see https://jpl.enterprise.slack.com/archives/GCGR1R3A4/p1712170107344829

**Comment by tloubrieu-jpl** [comment]
meeting is rescheduled this Monday.

**Comment by nutjob4life** [comment]
Successful meeting with @ramesh-maddegoda and @sjoshi-jpl with a number of takeaways:

-   Structure of Terraform into a top-level `main.tf` and subdirectories for specific "environments"
    -   For example, `mwaa-env` is the "Managed Airflow" environment
    -   You can re-use environments by repeating the `source` but substituting different variables
-   `terraform.tfvars` could contain secrets so it's best kept locally or in "private" GitHub repositories
-   Data blocks are generally for things "outside" Terraform, such as an IAM document already deployed in AWS
    -   Or for resources that were previously managed by Terraform
-   `depends_on = […]` handles dependencies during orchestration
-   The `.tfstate` file tracks the "state of everything"
    -   Locally this makes perfect sense
    -   In the cloud, you'll want `.tfstate` in a backed storage like S3
-   Some sample commands
    -   `terraform fmt` rewrites your Terraform files into a canonical style
    -   `terraform validate` checks the files
    -   `terraform plan -var-file=./tfvars/def.tfvars -lock=false` … shows the "plan of attack"
    -   `terraform apply -var-file=./tfvars/def.tfvars -lock=false` … "attack!"
        -   Note that depending on your vars, the same command works locally or all the way into the cloud
    -   `terraform destory -auto-approve` … "retreat!" (brings it all down)
-   Best practices: https://www.terraform-best-practices.com/key-concepts

**Comment by tloubrieu-jpl** [comment]
This good for now.
