### ISSUE TITLE
Create workflows to utilize new roundup unstable/stable CI

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/devops#73]
### 💡 Description

We have the new unstable/stable CI created with roundup, but we need to workflow files added to the template repo and retrofitted into existing react repos.

**Comment by tloubrieu-jpl** [comment]
Here we want to configure the existing nodejs repository to use the new nodejs roundup CI.

**Comment by nutjob4life** [comment]
PRs open as of this writing:

- https://github.com/NASA-PDS/doi-ui/pull/236
- https://github.com/NASA-PDS/s3-browser-cloudfront/pull/40
- https://github.com/NASA-PDS/wds/pull/20

PRs approved and merged:

- https://github.com/NASA-PDS/atlas/pull/37
- https://github.com/NASA-PDS/template-repo-nodejs/pull/6
- https://github.com/NASA-PDS/wds-react-legacy/pull/198

PRs closed (wont merge):

- https://github.com/NASA-PDS/archive-viewer/pull/47

**Comment by nutjob4life** [comment]
Status of repositories as using Node.js (based on presence of `package.json` file):

| Repository              | Roundup CI |
|:------------------------|------------|
| `archive-viewer`        | Rejected   |
| `atlas`                 | Integrated |
| `doi-ui`                | Integrated |
| `portal-wp-smd`         | See note   |
| `s3-browser-awssdk`     | [Open PR](https://github.com/NASA-PDS/s3-browser-awssdk/pull/55) |
| `s3-browser-cloudfront` | Integrated |
| `template-repo-nodejs`  | Integrated |
| `wds`                   | Integrated |
| `wds-react`             | [Open PR](https://github.com/NASA-PDS/wds-react/pull/28) |
| `wds-react-legacy`      | Integrated |

Note: Should `portal-wp-smd` repository be a part of our EN CI/CD system?

**Comment by jordanpadams** [comment]
Status: To be reviewed by @eddiesarevalo

**Comment by anilnatha** [comment]
@nutjob4life `wds-react` PR has been reviewed.

**Comment by jordanpadams** [comment]
Closing this as done
