### ISSUE TITLE
As a developer, I want to ensure image dependencies are secure

### ISSUE THREAD

**Issue by nutjob4life** [NASA-PDS/devops#76]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Devops

### 💪 Motivation

...so that I can ensure the dependencies used in container images are secure and up-to-date.

A scanning tool such as [Grype](https://github.com/anchore/grype) can ensure that package dependencies, operating system versions, and language-specific vulnerabilities do not end up in generated images. Combined with a [pre-commit hook](https://pre-commit.com), this can prevent such security problems from proliferating into distributed images. [GitHub Actions](https://docs.github.com/en/actions) can ensure the safety of such images from contributions made without pre-commit hooks.

The [SLIM community](https://nasa-ammos.github.io/slim/) has an [in-progress guide](https://riverma.github.io/slim/docs/guides/software-lifecycle/security/dependency-vulnerability-scanning/) describing just this.

### Acceptance Criteria

**Given** 
**When I perform** 
**Then I expect**

**Comment by riverma** [comment]
Awesome @nutjob4life - interested to hear your experience with this tool and guide. SLIM is currently collecting feedback on how to improve the guide before we publish it to our site.

**Comment by tloubrieu-jpl** [comment]
Starting with validate.

**Comment by tloubrieu-jpl** [comment]
validate has many dependencies, some of them have vulnerabiliies.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl @nutjob4life do validate dependencies have vulnerabilities? between dependabot and sonatype, I am surprised we have not caught these. I monitor these closely.

**Comment by nutjob4life** [comment]
@jordanpadams, yes, validate depended on pds4-jparser, which depended on pds-opencsv, which depended on commons-text:1.9, which had a critical vulnerability (detected using Grype, the container image-scanning tool).

Dependabot caught it roughly the same time I did!

**Comment by jordanpadams** [comment]
Status: Completed on validate. Will add more sub-tasks for adding this other repos as they come up.

other higher priority repos in the future:
* Registry API
* Registry Loader Tools

**Comment by jordanpadams** [comment]
Closed per https://github.com/NASA-PDS/validate/pull/1010. Will create new tasks for future expansion to other repos

**Comment by jordanpadams** [comment]
Skipping I&T. Not critical to test as this is an internal repo check.

**Comment by jordanpadams** [comment]
These changes were actually reverted anyways.

@nutjob4life do we remember why we reverted those updates?

**Comment by nutjob4life** [comment]
@jordanpadams two reasons as I recall:

1. The tool that the SLIM folks recommended ("Grype") does not work with multiplatform images—which we definitely use
2. Dependabot already does a fine job of detecting vulnerabilties anyway

**Comment by jordanpadams** [comment]
Copy. Thanks @nutjob4life
